var require = {
    'baseUrl': '/lg4-common-gp/js',
    'waitSeconds': 0,
    'paths': {
        'common': 'common',
        'jquery': '../bower_components/jquery/jquery.min',
        //'jquery': '../bower_components/jquery/dist/jquery',
        // 'jquery': '../bower_components/jquery-legacy/jquery',
        'jqueryui': '../bower_components/jqueryui/ui/minified/jquery-ui.min',
        'modernizr': '../bower_components/modernizr/modernizr',
        'text': '../bower_components/requirejs-text/text',
        'ic': '../bower_components/ic/lib',
        'fastclick': '../bower_components/fastclick/lib/fastclick',
        'swipe': '../bower_components/swipe/swipe',
        'slick-carousel': '../bower_components/slick-carousel_new/slick/slick',
        'jquery.cookie': '../bower_components/jquery.cookie/jquery.cookie',
        'lodash': '../bower_components/lodash/dist/lodash',
        'gremlins': '../bower_components/gremlins.js/gremlins.min',
        'chosen': '../bower_components/bower-chosen-master/chosen.jquery',
        'touchswipe': '../bower_components/jquery.touchSwipe/jquery.touchSwipe',
        'lazyload': 'common/lazyload',
        'browser-alert': 'common/browser-alert',
        'localize': 'common/localize',
        'simple-template': '../bower_components/ic/lib/util/simple-template',
        /* PJTBTOBCSR-138 */
        "accordion": 'support/component/accordion',
        /* //PJTBTOBCSR-138 */
        'react-dotdotdot': '../bower_components/jQuery.dotdotdot-master/src/jquery.dotdotdot',//LGEGMO-3850 : 20180306 add

        // product
        'mkt/app-tabs': 'products/component/app-tabs',
        'mkt/filter': 'products/component/filter',
        'mkt/find-a-store': 'products/component/find-a-store',
        'mkt/find-the-right': 'products/component/find-the-right',
        'mkt/find-the-right-filter': 'products/component/find-the-right-filter',
        'mkt/group-slick': 'products/component/group-slick',
        'mkt/legal': 'products/component/legal',
        'mkt/product-stickynav': 'products/component/product-stickynav',
        'mkt/product-cookie': 'products/component/product-cookie',
        'mkt/product-hero': 'products/component/product-hero',
        'mkt/product-lazy': 'products/component/product-lazy',
        'mkt/product-lists-carousel': 'products/component/product-lists-carousel',
        'mkt/product-lists-view-more': 'products/component/product-lists-view-more',
        'mkt/product-ask': 'products/component/product-ask',
        'mkt/product-compare': 'products/component/product-compare',
        'mkt/product-detail': 'products/component/product-detail',
        'mkt/product-zoom': 'products/component/product-zoom',
        'mkt/site-map': 'products/component/site-map',
        'mkt/where-to-buy': 'products/component/where-to-buy',
        'mkt/where-to-buy-map': 'products/component/where-to-buy-map',
        'mkt/where-to-buy-map_cn': 'products/component/where-to-buy-map_cn',
        'mkt/where-to-buy-map_ru': 'products/component/where-to-buy-map_ru',
        'mkt/scrollbar': 'products/component/scrollbar',
        'mkt/infobox': 'products/component/infobox',
        'mkt/infobox_cn': 'products/component/infobox_cn',
        'mkt/product-stepchart': 'products/module/product-stepchart',
        'mkt/product-video': 'products/module/product-video',
        'mkt/text-more': 'products/module/text-more',
        'mkt/hero-carousel': 'hero/hero-carousel',
        'mkt/call-to-action-carousel': 'call-to-action/call-to-action-carousel',
        'mkt/touch-punch': 'common/touch-punch',
        'mkt/search-result': 'common/search-result',
        'mkt/e-smart-zoom-jquery': 'common/e-smart-zoom-jquery',
        'mkt/slider-select': 'products/component/slider-select',
        'mkt/videoload': 'products/component/videoload',
        'mkt/basicmotion': 'products/component/basicmotion',
        'mkt/modelsticky': 'products/component/product-model-stickynav',
        'mkt/file-download': 'products/component/file-download',
        'mkt/tooltip': 'products/component/tooltip',
        'mkt/forms': 'products/component/forms',
        'mkt/spin': 'products/component/spin',
        'mkt/styledform': 'products/component/styledform',

        /* LGEPJT-91 */
        //b2b
        'mkt/find-map': 'business/find-map',
        'mkt/find-map_cn': 'business/find-map_cn',
        'mkt/find-infobox': 'business/find-infobox',
        'mkt/find-infobox_cn': 'business/find-infobox_cn',
        'mkt/business-forms': 'business/business-forms',
        'mkt/inquiry-to-buy': 'business/inquiry-to-buy',
        'mkt/resources' : 'business/resources',
        'mkt/floating' : 'business/floating',
        'mkt/video' : 'business/video',
        /* //LGEPJT-91 */


        // cs
        'cs': 'support/component', // cs path
        'cs/datepicker': 'support/component/datepicker',
        'cs/modallayer': 'support/component/modallayer',
        'cs/placeholder': 'support/component/placeholder',
        'cs/predictive': 'support/component/predictive-search',
        'cs/scrollbar': 'support/component/scrollbar',
        'cs/styledform': 'support/component/styledform',
        'cs/tooltiplayer': 'support/component/tooltiplayer',
        'cs/validation': 'support/component/validation',
        'cs/forms': 'support/component/forms',
        'cs/basicmotion': 'support/component/basicmotion',
        'cs/tabpanel': 'support/component/tabpanel',
        'cs/fileupload': 'support/component/fileupload',
        'cs/repairmap': 'support/component/repairmap',
        'cs/repairmap_baidu': 'support/component/repairmap_baidu',
        'cs/infobox': 'support/component/infobox',
        'cs/droplist': 'support/component/droplist',
        'cs/dropdown': 'support/component/dropdown',
        'cs/gmapload': 'support/component/gmap',
        'cs/videoload': 'support/component/videoload',
        'cs/pagination': 'support/component/pagination',
        'cs/rwdImageMaps': 'support/component/rwdImageMaps',
        'cs/spin': 'support/component/spin',
        'cs/ajaxform': 'support/component/ajaxform',
        'cs/maskedinput': 'support/component/maskedinput',
        'support/product-selector': 'support/module/product-selector',
        'support/model-selector': 'support/module/model-selector',
        'support/step-list': 'support/module/step-list',
        'support/feedback': 'support/module/feedback',
        'support/sticky': 'support/module/sticky',
        'support/share-email-sms': 'support/module/share-email-sms',
        'cs/printshiv': 'support/component/html5shiv-printshiv',
        'center-text': 'support/component/center-text',
        'cs/model-browser': 'support/module/model-browser', //** added **
        /* PJTBTOBCSR-138 */
        'cs/warranty': 'support/component/warranty',
        /* //PJTBTOBCSR-138 */

        // social login
        'loginapi': 'support/component/loginapi',
        /* PJTBTOBCSR-138 */
        'cs/registerProduct': 'support/_myaccount/register-product',
        /* //PJTBTOBCSR-138 */

        /* PJTPDP-11 */
        'mkt/product-pdp-improv': 'products/component/product-pdp-improv',
        'mkt/product-pdp-mobile': 'products/component/product-pdp-mobile',
        'mkt/pdp-tabs': 'products/component/pdp-tabs',
        'slick-carousel-pdp': 'products/component/slick-pdp',
        'mkt/panzoom':'common/panzoom',
        'mkt/sticky-pdp':'products/component/sticky-pdp',
        'mkt/hammer':'common/hammer.min'
        /*//PJTPDP-11 */
    },
    'shim': {
        'swipe': {
            'exports': 'Swipe'
        },
        'jqueryui': ['jquery'],
        'global': ['jquery'],
        'chosen': ['jquery'],
        'products': ['jquery', 'global'],
        'aboutlg': ['jquery', 'global'],
        'lazyload': ['common/preload'],
        'slick-carousel': ['common/msg', 'common/preload'],
        'support': ['jquery', 'global', 'modernizr'],
        'support/product-selector': ['cs/modallayer', 'cs/predictive'],
        'support/sticky': ['lazyload'],
        'cs/modallayer': ['jquery', 'cs/tabpanel', 'cs/forms'],
        'cs/datepicker': ['jquery'],
        'cs/basicmotion': ['jquery'],
        'cs/styledform': ['jquery'],
        'cs/rwdImageMaps': ['jquery'],
        'cs/scrollbar': ['jquery', 'cs/dropdown'],
        'cs/dropdown': ['jquery', 'cs/forms'],
        'cs/droplist': ['jquery', 'cs/forms'],
        'cs/spin': ['jquery'],
        'localize': ['jquery', 'modernizr', 'common', 'ic']
    },
    'packages': ['global', 'products', 'support', 'authoring', 'support/_myaccount', 'support/_repair', 'support/_request', 'support/_etc', 'aboutlg', 'localize']
}
